"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aqualink_sdk
from aqualink_sdk.model.site import Site
from aqualink_sdk.model.site_survey_point import SiteSurveyPoint
globals()['Site'] = Site
globals()['SiteSurveyPoint'] = SiteSurveyPoint
from aqualink_sdk.model.data_uploads import DataUploads


class TestDataUploads(unittest.TestCase):
    """DataUploads unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataUploads(self):
        """Test DataUploads"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DataUploads()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
