"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aqualink_sdk
from aqualink_sdk.model.survey_media_sensor_data_hobo import SurveyMediaSensorDataHobo
from aqualink_sdk.model.survey_media_sensor_data_noaa import SurveyMediaSensorDataNoaa
from aqualink_sdk.model.survey_media_sensor_data_spotter import SurveyMediaSensorDataSpotter
globals()['SurveyMediaSensorDataHobo'] = SurveyMediaSensorDataHobo
globals()['SurveyMediaSensorDataNoaa'] = SurveyMediaSensorDataNoaa
globals()['SurveyMediaSensorDataSpotter'] = SurveyMediaSensorDataSpotter
from aqualink_sdk.model.survey_media_sensor_data import SurveyMediaSensorData


class TestSurveyMediaSensorData(unittest.TestCase):
    """SurveyMediaSensorData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSurveyMediaSensorData(self):
        """Test SurveyMediaSensorData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SurveyMediaSensorData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
