"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import aqualink_sdk
from aqualink_sdk.api.site_points_of_interest_api import SitePointsOfInterestApi  # noqa: E501


class TestSitePointsOfInterestApi(unittest.TestCase):
    """SitePointsOfInterestApi unit test stubs"""

    def setUp(self):
        self.api = SitePointsOfInterestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_site_survey_points_controller_create(self):
        """Test case for site_survey_points_controller_create

        Creates a new site point of interest  # noqa: E501
        """
        pass

    def test_site_survey_points_controller_delete(self):
        """Test case for site_survey_points_controller_delete

        Deletes specified site point of interest  # noqa: E501
        """
        pass

    def test_site_survey_points_controller_find(self):
        """Test case for site_survey_points_controller_find

        Returns site points of interest filtered by the provided filters  # noqa: E501
        """
        pass

    def test_site_survey_points_controller_find_one(self):
        """Test case for site_survey_points_controller_find_one

        Returns specified site point of interest  # noqa: E501
        """
        pass

    def test_site_survey_points_controller_update(self):
        """Test case for site_survey_points_controller_update

        Updates specified site point of interest  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
