# coding: utf-8

"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_site_survey_point_dto import UpdateSiteSurveyPointDto  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateSiteSurveyPointDto(unittest.TestCase):
    """UpdateSiteSurveyPointDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateSiteSurveyPointDto(self):
        """Test UpdateSiteSurveyPointDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_site_survey_point_dto.UpdateSiteSurveyPointDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
