"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aqualink_sdk
from aqualink_sdk.model.inline_response200_sofar_wave_model_wind_gust_speed import InlineResponse200SofarWaveModelWindGustSpeed
globals()['InlineResponse200SofarWaveModelWindGustSpeed'] = InlineResponse200SofarWaveModelWindGustSpeed
from aqualink_sdk.model.inline_response200_sofar_wave_model import InlineResponse200SofarWaveModel


class TestInlineResponse200SofarWaveModel(unittest.TestCase):
    """InlineResponse200SofarWaveModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200SofarWaveModel(self):
        """Test InlineResponse200SofarWaveModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse200SofarWaveModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
