"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aqualink_sdk
from aqualink_sdk.model.collection_data_dto import CollectionDataDto
from aqualink_sdk.model.historical_monthly_mean import HistoricalMonthlyMean
from aqualink_sdk.model.region import Region
from aqualink_sdk.model.region_polygon import RegionPolygon
from aqualink_sdk.model.site_application import SiteApplication
from aqualink_sdk.model.sofar_live_data_dto import SofarLiveDataDto
from aqualink_sdk.model.survey import Survey
from aqualink_sdk.model.user import User
from aqualink_sdk.model.video_stream import VideoStream
globals()['CollectionDataDto'] = CollectionDataDto
globals()['HistoricalMonthlyMean'] = HistoricalMonthlyMean
globals()['Region'] = Region
globals()['RegionPolygon'] = RegionPolygon
globals()['SiteApplication'] = SiteApplication
globals()['SofarLiveDataDto'] = SofarLiveDataDto
globals()['Survey'] = Survey
globals()['User'] = User
globals()['VideoStream'] = VideoStream
from aqualink_sdk.model.site import Site


class TestSite(unittest.TestCase):
    """Site unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSite(self):
        """Test Site"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Site()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
