"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aqualink_sdk
from aqualink_sdk.model.set_admin_level_dto import SetAdminLevelDto


class TestSetAdminLevelDto(unittest.TestCase):
    """SetAdminLevelDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetAdminLevelDto(self):
        """Test SetAdminLevelDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SetAdminLevelDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
