"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aqualink_sdk
from aqualink_sdk.model.inline_response2001_sofar_wave_model_wind_gust_speed import InlineResponse2001SofarWaveModelWindGustSpeed
globals()['InlineResponse2001SofarWaveModelWindGustSpeed'] = InlineResponse2001SofarWaveModelWindGustSpeed
from aqualink_sdk.model.inline_response2001_sofar_wave_model import InlineResponse2001SofarWaveModel


class TestInlineResponse2001SofarWaveModel(unittest.TestCase):
    """InlineResponse2001SofarWaveModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001SofarWaveModel(self):
        """Test InlineResponse2001SofarWaveModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2001SofarWaveModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
