# coding: utf-8

"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sensors_api import SensorsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSensorsApi(unittest.TestCase):
    """SensorsApi unit test stubs"""

    def setUp(self):
        self.api = SensorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sensors_controller_find_sensor_data(self):
        """Test case for sensors_controller_find_sensor_data

        Get data from a specified sensor  # noqa: E501
        """
        pass

    def test_sensors_controller_find_sensor_surveys(self):
        """Test case for sensors_controller_find_sensor_surveys

        Get surveys and survey media from a specified sensor  # noqa: E501
        """
        pass

    def test_sensors_controller_find_sensors(self):
        """Test case for sensors_controller_find_sensors

        Get all sites having sensors  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
