"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aqualink_sdk
from aqualink_sdk.model.time_series_value_dto import TimeSeriesValueDto
globals()['TimeSeriesValueDto'] = TimeSeriesValueDto
from aqualink_sdk.model.spotter_data_dto import SpotterDataDto


class TestSpotterDataDto(unittest.TestCase):
    """SpotterDataDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpotterDataDto(self):
        """Test SpotterDataDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SpotterDataDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
