"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import aqualink_sdk
from aqualink_sdk.api.sensors_api import SensorsApi  # noqa: E501


class TestSensorsApi(unittest.TestCase):
    """SensorsApi unit test stubs"""

    def setUp(self):
        self.api = SensorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sensors_controller_find_sensor_data(self):
        """Test case for sensors_controller_find_sensor_data

        Get data from a specified sensor  # noqa: E501
        """
        pass

    def test_sensors_controller_find_sensor_surveys(self):
        """Test case for sensors_controller_find_sensor_surveys

        Get surveys and survey media from a specified sensor  # noqa: E501
        """
        pass

    def test_sensors_controller_find_sensors(self):
        """Test case for sensors_controller_find_sensors

        Get all sites having sensors  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
