"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import aqualink_sdk
from aqualink_sdk.api.regions_api import RegionsApi  # noqa: E501


class TestRegionsApi(unittest.TestCase):
    """RegionsApi unit test stubs"""

    def setUp(self):
        self.api = RegionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_regions_controller_create(self):
        """Test case for regions_controller_create

        Creates new region  # noqa: E501
        """
        pass

    def test_regions_controller_delete(self):
        """Test case for regions_controller_delete

        Deletes specified region  # noqa: E501
        """
        pass

    def test_regions_controller_find(self):
        """Test case for regions_controller_find

        Returns regions filtered by provided filters  # noqa: E501
        """
        pass

    def test_regions_controller_find_one(self):
        """Test case for regions_controller_find_one

        Returns specified region  # noqa: E501
        """
        pass

    def test_regions_controller_update(self):
        """Test case for regions_controller_update

        Updates specified region  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
