"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aqualink_sdk
from aqualink_sdk.model.time_series_point import TimeSeriesPoint
globals()['TimeSeriesPoint'] = TimeSeriesPoint
from aqualink_sdk.model.survey_media_sensor_data_noaa import SurveyMediaSensorDataNoaa


class TestSurveyMediaSensorDataNoaa(unittest.TestCase):
    """SurveyMediaSensorDataNoaa unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSurveyMediaSensorDataNoaa(self):
        """Test SurveyMediaSensorDataNoaa"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SurveyMediaSensorDataNoaa()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
