"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aqualink_sdk
from aqualink_sdk.model.site import Site
globals()['Site'] = Site
from aqualink_sdk.model.historical_monthly_mean import HistoricalMonthlyMean


class TestHistoricalMonthlyMean(unittest.TestCase):
    """HistoricalMonthlyMean unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHistoricalMonthlyMean(self):
        """Test HistoricalMonthlyMean"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HistoricalMonthlyMean()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
