"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aqualink_sdk
from aqualink_sdk.model.edit_survey_dto import EditSurveyDto


class TestEditSurveyDto(unittest.TestCase):
    """EditSurveyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditSurveyDto(self):
        """Test EditSurveyDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EditSurveyDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
