# coding: utf-8

"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.set_admin_level_dto import SetAdminLevelDto  # noqa: E501
from swagger_client.rest import ApiException


class TestSetAdminLevelDto(unittest.TestCase):
    """SetAdminLevelDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetAdminLevelDto(self):
        """Test SetAdminLevelDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.set_admin_level_dto.SetAdminLevelDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
