# coding: utf-8

"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import aqualink_sdk
from aqualink_sdk.models.inline_response2001_metlog import InlineResponse2001Metlog  # noqa: E501
from aqualink_sdk.rest import ApiException


class TestInlineResponse2001Metlog(unittest.TestCase):
    """InlineResponse2001Metlog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001Metlog(self):
        """Test InlineResponse2001Metlog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aqualink_sdk.models.inline_response2001_metlog.InlineResponse2001Metlog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
