# coding: utf-8

"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import aqualink_sdk
from aqualink_sdk.models.survey_media_sensor_data_spotter import SurveyMediaSensorDataSpotter  # noqa: E501
from aqualink_sdk.rest import ApiException


class TestSurveyMediaSensorDataSpotter(unittest.TestCase):
    """SurveyMediaSensorDataSpotter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSurveyMediaSensorDataSpotter(self):
        """Test SurveyMediaSensorDataSpotter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aqualink_sdk.models.survey_media_sensor_data_spotter.SurveyMediaSensorDataSpotter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
