"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aqualink_sdk
from aqualink_sdk.model.sofar_live_data_dto_site import SofarLiveDataDtoSite


class TestSofarLiveDataDtoSite(unittest.TestCase):
    """SofarLiveDataDtoSite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSofarLiveDataDtoSite(self):
        """Test SofarLiveDataDtoSite"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SofarLiveDataDtoSite()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
