# coding: utf-8

"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import aqualink_sdk
from aqualink_sdk.models.inline_response2001_metlog_wind_gust_speed import InlineResponse2001MetlogWindGustSpeed  # noqa: E501
from aqualink_sdk.rest import ApiException


class TestInlineResponse2001MetlogWindGustSpeed(unittest.TestCase):
    """InlineResponse2001MetlogWindGustSpeed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001MetlogWindGustSpeed(self):
        """Test InlineResponse2001MetlogWindGustSpeed"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aqualink_sdk.models.inline_response2001_metlog_wind_gust_speed.InlineResponse2001MetlogWindGustSpeed()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
