"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import aqualink_sdk
from aqualink_sdk.api.collections_api import CollectionsApi  # noqa: E501


class TestCollectionsApi(unittest.TestCase):
    """CollectionsApi unit test stubs"""

    def setUp(self):
        self.api = CollectionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_collections_controller_create(self):
        """Test case for collections_controller_create

        Creates a new collection  # noqa: E501
        """
        pass

    def test_collections_controller_delete(self):
        """Test case for collections_controller_delete

        Delete specified collection  # noqa: E501
        """
        pass

    def test_collections_controller_find(self):
        """Test case for collections_controller_find

        Fetch all user's private collections  # noqa: E501
        """
        pass

    def test_collections_controller_find_one(self):
        """Test case for collections_controller_find_one

        Fetch detailed data from specified private collection  # noqa: E501
        """
        pass

    def test_collections_controller_find_one_public(self):
        """Test case for collections_controller_find_one_public

        Fetch detailed data from specified public collection  # noqa: E501
        """
        pass

    def test_collections_controller_find_public(self):
        """Test case for collections_controller_find_public

        Fetch all public collections  # noqa: E501
        """
        pass

    def test_collections_controller_get_heat_stress_tracker(self):
        """Test case for collections_controller_get_heat_stress_tracker

        Fetch the heat stress tracker  # noqa: E501
        """
        pass

    def test_collections_controller_update(self):
        """Test case for collections_controller_update

        Update specified collection  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
