# coding: utf-8

"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.site_applications_api import SiteApplicationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSiteApplicationsApi(unittest.TestCase):
    """SiteApplicationsApi unit test stubs"""

    def setUp(self):
        self.api = SiteApplicationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_site_applications_controller_find_one_from_site(self):
        """Test case for site_applications_controller_find_one_from_site

        Returns site application of specified site  # noqa: E501
        """
        pass

    def test_site_applications_controller_update(self):
        """Test case for site_applications_controller_update

        Updates site application by providing its appId. Needs authentication.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
