"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import aqualink_sdk
from aqualink_sdk.api.google_cloud_storage_api import GoogleCloudStorageApi  # noqa: E501


class TestGoogleCloudStorageApi(unittest.TestCase):
    """GoogleCloudStorageApi unit test stubs"""

    def setUp(self):
        self.api = GoogleCloudStorageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_google_cloud_controller_delete_dangling_files(self):
        """Test case for google_cloud_controller_delete_dangling_files

        Deletes all unused files stored  # noqa: E501
        """
        pass

    def test_google_cloud_controller_find_dangling_files(self):
        """Test case for google_cloud_controller_find_dangling_files

        Returns all files stored that are not used  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
