# coding: utf-8

"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.create_user_dto import CreateUserDto  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateUserDto(unittest.TestCase):
    """CreateUserDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateUserDto(self):
        """Test CreateUserDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.create_user_dto.CreateUserDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
