"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aqualink_sdk
from aqualink_sdk.model.region_polygon import RegionPolygon


class TestRegionPolygon(unittest.TestCase):
    """RegionPolygon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegionPolygon(self):
        """Test RegionPolygon"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RegionPolygon()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
