"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aqualink_sdk
from aqualink_sdk.model.latest_data import LatestData
from aqualink_sdk.model.sofar_live_data_dto_site import SofarLiveDataDtoSite
from aqualink_sdk.model.sofar_live_data_dto_spotter_position import SofarLiveDataDtoSpotterPosition
from aqualink_sdk.model.time_series_value_dto import TimeSeriesValueDto
globals()['LatestData'] = LatestData
globals()['SofarLiveDataDtoSite'] = SofarLiveDataDtoSite
globals()['SofarLiveDataDtoSpotterPosition'] = SofarLiveDataDtoSpotterPosition
globals()['TimeSeriesValueDto'] = TimeSeriesValueDto
from aqualink_sdk.model.sofar_live_data_dto import SofarLiveDataDto


class TestSofarLiveDataDto(unittest.TestCase):
    """SofarLiveDataDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSofarLiveDataDto(self):
        """Test SofarLiveDataDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SofarLiveDataDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
