# coding: utf-8

"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.site_points_of_interest_api import SitePointsOfInterestApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSitePointsOfInterestApi(unittest.TestCase):
    """SitePointsOfInterestApi unit test stubs"""

    def setUp(self):
        self.api = SitePointsOfInterestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_site_survey_points_controller_create(self):
        """Test case for site_survey_points_controller_create

        Creates a new site point of interest  # noqa: E501
        """
        pass

    def test_site_survey_points_controller_delete(self):
        """Test case for site_survey_points_controller_delete

        Deletes specified site point of interest  # noqa: E501
        """
        pass

    def test_site_survey_points_controller_find(self):
        """Test case for site_survey_points_controller_find

        Returns site points of interest filtered by the provided filters  # noqa: E501
        """
        pass

    def test_site_survey_points_controller_find_one(self):
        """Test case for site_survey_points_controller_find_one

        Returns specified site point of interest  # noqa: E501
        """
        pass

    def test_site_survey_points_controller_update(self):
        """Test case for site_survey_points_controller_update

        Updates specified site point of interest  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
