"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aqualink_sdk
from aqualink_sdk.model.site import Site
from aqualink_sdk.model.user import User
globals()['Site'] = Site
globals()['User'] = User
from aqualink_sdk.model.site_application import SiteApplication


class TestSiteApplication(unittest.TestCase):
    """SiteApplication unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSiteApplication(self):
        """Test SiteApplication"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SiteApplication()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
