# flake8: noqa

"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from aqualink_sdk.api_client import ApiClient

# import Configuration
from aqualink_sdk.configuration import Configuration

# import exceptions
from aqualink_sdk.exceptions import OpenApiException
from aqualink_sdk.exceptions import ApiAttributeError
from aqualink_sdk.exceptions import ApiTypeError
from aqualink_sdk.exceptions import ApiValueError
from aqualink_sdk.exceptions import ApiKeyError
from aqualink_sdk.exceptions import ApiException
