# coding: utf-8

"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExclusionDates(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'float',
        'sensor_id': 'str',
        'start_date': 'datetime',
        'end_date': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'sensor_id': 'sensorId',
        'start_date': 'startDate',
        'end_date': 'endDate'
    }

    def __init__(self, id=None, sensor_id=None, start_date=None, end_date=None):  # noqa: E501
        """ExclusionDates - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._sensor_id = None
        self._start_date = None
        self._end_date = None
        self.discriminator = None
        self.id = id
        self.sensor_id = sensor_id
        self.start_date = start_date
        self.end_date = end_date

    @property
    def id(self):
        """Gets the id of this ExclusionDates.  # noqa: E501


        :return: The id of this ExclusionDates.  # noqa: E501
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ExclusionDates.


        :param id: The id of this ExclusionDates.  # noqa: E501
        :type: float
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def sensor_id(self):
        """Gets the sensor_id of this ExclusionDates.  # noqa: E501


        :return: The sensor_id of this ExclusionDates.  # noqa: E501
        :rtype: str
        """
        return self._sensor_id

    @sensor_id.setter
    def sensor_id(self, sensor_id):
        """Sets the sensor_id of this ExclusionDates.


        :param sensor_id: The sensor_id of this ExclusionDates.  # noqa: E501
        :type: str
        """
        if sensor_id is None:
            raise ValueError("Invalid value for `sensor_id`, must not be `None`")  # noqa: E501

        self._sensor_id = sensor_id

    @property
    def start_date(self):
        """Gets the start_date of this ExclusionDates.  # noqa: E501


        :return: The start_date of this ExclusionDates.  # noqa: E501
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this ExclusionDates.


        :param start_date: The start_date of this ExclusionDates.  # noqa: E501
        :type: datetime
        """
        if start_date is None:
            raise ValueError("Invalid value for `start_date`, must not be `None`")  # noqa: E501

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this ExclusionDates.  # noqa: E501


        :return: The end_date of this ExclusionDates.  # noqa: E501
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this ExclusionDates.


        :param end_date: The end_date of this ExclusionDates.  # noqa: E501
        :type: datetime
        """
        if end_date is None:
            raise ValueError("Invalid value for `end_date`, must not be `None`")  # noqa: E501

        self._end_date = end_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExclusionDates, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExclusionDates):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
