"""
    Aqualink API documentation

    The Aqualink public API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from aqualink_sdk.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from aqualink_sdk.exceptions import ApiAttributeError


def lazy_import():
    from aqualink_sdk.model.site import Site
    globals()['Site'] = Site


class DailyData(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'id': (float,),  # noqa: E501
            'min_bottom_temperature': (float, none_type,),  # noqa: E501
            'max_bottom_temperature': (float, none_type,),  # noqa: E501
            'avg_bottom_temperature': (float, none_type,),  # noqa: E501
            'degree_heating_days': (float, none_type,),  # noqa: E501
            'top_temperature': (float, none_type,),  # noqa: E501
            'satellite_temperature': (float, none_type,),  # noqa: E501
            'min_wave_height': (float, none_type,),  # noqa: E501
            'max_wave_height': (float, none_type,),  # noqa: E501
            'avg_wave_height': (float, none_type,),  # noqa: E501
            'wave_mean_direction': (float, none_type,),  # noqa: E501
            'wave_peak_period': (float, none_type,),  # noqa: E501
            'wave_mean_period': (float, none_type,),  # noqa: E501
            'min_wind_speed': (float, none_type,),  # noqa: E501
            'max_wind_speed': (float, none_type,),  # noqa: E501
            'avg_wind_speed': (float, none_type,),  # noqa: E501
            'wind_direction': (float, none_type,),  # noqa: E501
            'daily_alert_level': (float, none_type,),  # noqa: E501
            'weekly_alert_level': (float, none_type,),  # noqa: E501
            'date': (datetime,),  # noqa: E501
            'site': (Site,),  # noqa: E501
            'created_at': (datetime,),  # noqa: E501
            'updated_at': (datetime,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'id': 'id',  # noqa: E501
        'min_bottom_temperature': 'minBottomTemperature',  # noqa: E501
        'max_bottom_temperature': 'maxBottomTemperature',  # noqa: E501
        'avg_bottom_temperature': 'avgBottomTemperature',  # noqa: E501
        'degree_heating_days': 'degreeHeatingDays',  # noqa: E501
        'top_temperature': 'topTemperature',  # noqa: E501
        'satellite_temperature': 'satelliteTemperature',  # noqa: E501
        'min_wave_height': 'minWaveHeight',  # noqa: E501
        'max_wave_height': 'maxWaveHeight',  # noqa: E501
        'avg_wave_height': 'avgWaveHeight',  # noqa: E501
        'wave_mean_direction': 'waveMeanDirection',  # noqa: E501
        'wave_peak_period': 'wavePeakPeriod',  # noqa: E501
        'wave_mean_period': 'waveMeanPeriod',  # noqa: E501
        'min_wind_speed': 'minWindSpeed',  # noqa: E501
        'max_wind_speed': 'maxWindSpeed',  # noqa: E501
        'avg_wind_speed': 'avgWindSpeed',  # noqa: E501
        'wind_direction': 'windDirection',  # noqa: E501
        'daily_alert_level': 'dailyAlertLevel',  # noqa: E501
        'weekly_alert_level': 'weeklyAlertLevel',  # noqa: E501
        'date': 'date',  # noqa: E501
        'site': 'site',  # noqa: E501
        'created_at': 'createdAt',  # noqa: E501
        'updated_at': 'updatedAt',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, id, min_bottom_temperature, max_bottom_temperature, avg_bottom_temperature, degree_heating_days, top_temperature, satellite_temperature, min_wave_height, max_wave_height, avg_wave_height, wave_mean_direction, wave_peak_period, wave_mean_period, min_wind_speed, max_wind_speed, avg_wind_speed, wind_direction, daily_alert_level, weekly_alert_level, date, site, created_at, updated_at, *args, **kwargs):  # noqa: E501
        """DailyData - a model defined in OpenAPI

        Args:
            id (float):
            min_bottom_temperature (float, none_type):
            max_bottom_temperature (float, none_type):
            avg_bottom_temperature (float, none_type):
            degree_heating_days (float, none_type):
            top_temperature (float, none_type):
            satellite_temperature (float, none_type):
            min_wave_height (float, none_type):
            max_wave_height (float, none_type):
            avg_wave_height (float, none_type):
            wave_mean_direction (float, none_type):
            wave_peak_period (float, none_type):
            wave_mean_period (float, none_type):
            min_wind_speed (float, none_type):
            max_wind_speed (float, none_type):
            avg_wind_speed (float, none_type):
            wind_direction (float, none_type):
            daily_alert_level (float, none_type):
            weekly_alert_level (float, none_type):
            date (datetime):
            site (Site):
            created_at (datetime):
            updated_at (datetime):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.id = id
        self.min_bottom_temperature = min_bottom_temperature
        self.max_bottom_temperature = max_bottom_temperature
        self.avg_bottom_temperature = avg_bottom_temperature
        self.degree_heating_days = degree_heating_days
        self.top_temperature = top_temperature
        self.satellite_temperature = satellite_temperature
        self.min_wave_height = min_wave_height
        self.max_wave_height = max_wave_height
        self.avg_wave_height = avg_wave_height
        self.wave_mean_direction = wave_mean_direction
        self.wave_peak_period = wave_peak_period
        self.wave_mean_period = wave_mean_period
        self.min_wind_speed = min_wind_speed
        self.max_wind_speed = max_wind_speed
        self.avg_wind_speed = avg_wind_speed
        self.wind_direction = wind_direction
        self.daily_alert_level = daily_alert_level
        self.weekly_alert_level = weekly_alert_level
        self.date = date
        self.site = site
        self.created_at = created_at
        self.updated_at = updated_at
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, id, min_bottom_temperature, max_bottom_temperature, avg_bottom_temperature, degree_heating_days, top_temperature, satellite_temperature, min_wave_height, max_wave_height, avg_wave_height, wave_mean_direction, wave_peak_period, wave_mean_period, min_wind_speed, max_wind_speed, avg_wind_speed, wind_direction, daily_alert_level, weekly_alert_level, date, site, created_at, updated_at, *args, **kwargs):  # noqa: E501
        """DailyData - a model defined in OpenAPI

        Args:
            id (float):
            min_bottom_temperature (float, none_type):
            max_bottom_temperature (float, none_type):
            avg_bottom_temperature (float, none_type):
            degree_heating_days (float, none_type):
            top_temperature (float, none_type):
            satellite_temperature (float, none_type):
            min_wave_height (float, none_type):
            max_wave_height (float, none_type):
            avg_wave_height (float, none_type):
            wave_mean_direction (float, none_type):
            wave_peak_period (float, none_type):
            wave_mean_period (float, none_type):
            min_wind_speed (float, none_type):
            max_wind_speed (float, none_type):
            avg_wind_speed (float, none_type):
            wind_direction (float, none_type):
            daily_alert_level (float, none_type):
            weekly_alert_level (float, none_type):
            date (datetime):
            site (Site):
            created_at (datetime):
            updated_at (datetime):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.id = id
        self.min_bottom_temperature = min_bottom_temperature
        self.max_bottom_temperature = max_bottom_temperature
        self.avg_bottom_temperature = avg_bottom_temperature
        self.degree_heating_days = degree_heating_days
        self.top_temperature = top_temperature
        self.satellite_temperature = satellite_temperature
        self.min_wave_height = min_wave_height
        self.max_wave_height = max_wave_height
        self.avg_wave_height = avg_wave_height
        self.wave_mean_direction = wave_mean_direction
        self.wave_peak_period = wave_peak_period
        self.wave_mean_period = wave_mean_period
        self.min_wind_speed = min_wind_speed
        self.max_wind_speed = max_wind_speed
        self.avg_wind_speed = avg_wind_speed
        self.wind_direction = wind_direction
        self.daily_alert_level = daily_alert_level
        self.weekly_alert_level = weekly_alert_level
        self.date = date
        self.site = site
        self.created_at = created_at
        self.updated_at = updated_at
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
